baseURL = "/"
disableLanguages = []
disqusShortname = ""
googleAnalytics = "G-93FNJ1X1J8"
languageCode = "en-us"
languageName = "En"
paginate = "6"
summaryLength = "10"
theme = "github.com/themefisher/twenty-twenty-hugo"
title = "Dan Williams"
[markup.goldmark.renderer]
unsafe = true
[[menu.desktop]]
URL = "/blog"
name = "Blog"
weight = ""
[[menu.main]]
URL = "/"
name = "Home"
weight = 1
[[menu.main]]
URL = "about"
name = "About"
weight = 2
[[menu.main]]
URL = "blog"
name = "Blog"
weight = 3
[outputs]
home = ["HTML", "RSS", "JSON"]
[params]
author = "Dan Williams"
description = "This is meta description"
[params.banner]
heading = "Thoughts, ideas and work"
image = ""
[params.blog]
heading = "A namespace for innovation, technology and cloud computing."
[params.call_to_action]
button_label = "Contact Us"
button_url = "contact"
content = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis"
enable = false
title = "Contact us for more information."
[params.footer]
address = ""
content = "Gary Hamel"
copyright = "Copyright &copy; 2020 Dan Williams"
hours = ""
title = "“In a world of commoditized knowledge, the returns go to the companies who can produce non-standard knowledge.”"
[params.gallery]
enable = false
[[params.gallery.gallery_item]]
image = "images/2020-square-2.png"
[[params.gallery.gallery_item]]
image = "images/2020-square-1.png"
[params.social]
email = "dtawilliams@gmail.com"
facebook = ""
instagram = ""
linkedin = "https://www.linkedin.com/in/dtwilliams1/"
twitter = ""
yelp = "#"
[taxonomies]
author = "author"
category = "categories"
tag = "tags"
